name = "linkRepo"
description = "A LinkTree-like theme"
license = "EnergyDrink License"
homepage = ""
# The minimum version of Zola required
min_version = "0.13.0"
# An optional live demo URL
demo = "https://june.lacoloc.cafe"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = June"
homepage = "https://june.lacoloc.cafe"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "mdo"
homepage = "https://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"